"""user_updates

Revision ID: 9d33a22fefed
Revises: 71917474782d
Create Date: 2026-02-05 09:11:41.424748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d33a22fefed'
down_revision: Union[str, None] = '71917474782d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_calendar_outfits_id'), 'calendar_outfits', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_calendar_outfits_id'), table_name='calendar_outfits')
    # ### end Alembic commands ###
